# Site settings
title: SpinWang
description: DNS hijack your friends
domain: spin.wang
# TODO: Figure out how not to need this.
url: "http://spin.wang"

# Build settings
markdown: kramdown
permalink: pretty

# SpinWang
analytics_tracking_id: UA-10349264-3

ga_displayfeatures: true
ga_attribution: true
